"""initial migration

Revision ID: fba83081631d
Revises: 
Create Date: 2019-01-15 16:59:48.959638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba83081631d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_model', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('L_W_H', sa.String(length=20), nullable=True),
    sa.Column('front_rear_wheelbase', sa.String(length=20), nullable=True),
    sa.Column('suspension_length', sa.String(length=20), nullable=True),
    sa.Column('wheelbase', sa.Numeric(precision=10), nullable=True),
    sa.Column('cd', sa.Numeric(precision=10), nullable=True),
    sa.Column('quality', sa.Numeric(precision=10), nullable=True),
    sa.Column('Fuel_tank_capacity', sa.Numeric(precision=10), nullable=True),
    sa.Column('cargo_volume', sa.Numeric(precision=10), nullable=True),
    sa.Column('max_cargo_volume', sa.Numeric(precision=10), nullable=True),
    sa.Column('door_num', sa.Integer(), nullable=True),
    sa.Column('occupants_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('parm_id', sa.Integer(), nullable=True),
    sa.Column('car_name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10), nullable=True),
    sa.Column('register', sa.Date(), nullable=True),
    sa.Column('mileage', sa.Numeric(precision=10), nullable=True),
    sa.Column('annual_inspection', sa.Date(), nullable=True),
    sa.Column('insurance', sa.Date(), nullable=True),
    sa.Column('car_addr', sa.String(length=100), nullable=True),
    sa.Column('car_age', sa.String(length=20), nullable=True),
    sa.Column('img', sa.LargeBinary(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['parm_id'], ['parm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('parm')
    op.drop_table('model')
    op.drop_table('brand')
    # ### end Alembic commands ###
